#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
      password: 'ead123cs'

#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course-v2
#    username: postgres
#    password: 12345
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://cjcvyqwr:T5q-IJ-1vDAW5ZzE9erVjwVijjbYxdNC@jackal.rmq.cloudamqp.com/cjcvyqwr
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#      notificationCommandExchange: ead.notificationcommand
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#    key:
#      notificationCommandKey: ms.notification

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - refresh
#          - health